### ISSUE TITLE
执行 gradlew bintrayUpload 时提示错误

### ISSUE THREAD

**Issue by TonyZZX** [xiaopansky/android-library-publish-to-jcenter#1]
:library:bintrayUpload FAILED                                                            
               
FAILURE: Build failed with an exception.

Some problems were found with the configuration of task ':library:bintrayUpload'.
> No value has been specified for property 'packageName'.
> No value has been specified for property 'user'.
> No value has been specified for property 'apiKey'.

**Comment by xiaopansky** [comment]
看下这些属性是在哪个文件中配置的，这个文件应该是在module下面

**Comment by TonyZzx** [comment]
哦是的，我又重新配置了一下，可以上传了。但是最后只成功上传library-1.0.0.aar文件。
终端显示如下：
Parallel execution with configuration on demand is an incubating feature.
:library:bintrayUpload                                                                   
:library:bintrayUpload: file E:\Projects\SwipeBackLayout\library\build\libs\library-1.0.0-javadoc.jar could not be found.
:library:bintrayUpload: file E:\Projects\SwipeBackLayout\library\build\libs\library-1.0.0-sources.jar could not be found.
Skipping upload for missing file 'E:\Projects\SwipeBackLayout\library\build\poms\pom-default.xml'.
如果我手动javadoc任务就会发生错误，我怀疑和我在library中compile 'com.android.support:appcompat-v7:23.0.0' 有关，请问一下有什么解决办法吗？
我的源码在这里 [library](https://github.com/TonyZzx/SwipeBackLayout/tree/master/library)

**Comment by xiaopansky** [comment]
你看下编译时候的日志 执行javadoc或sources的时候 如果出错了会有相关输出的，还要具体看什么原因

**Comment by TonyZzx** [comment]
提示就是所有涉及compile的import的包都被打上了问号，例如support v4的包

**Comment by xiaopansky** [comment]
你加我QQ 给我截图 我瞅瞅 八六七七四零四四

**Comment by fangyucun** [comment]
如何解决No value has been specified for property 'packageName'

**Comment by xiaopansky** [comment]
找不到packageName属性 是你项目配置有问题 没有编译成功 具体哪里配置的有问题 仅凭这句话我也判断不出来 你好好检查一下  或者你先去掉对android-library-publish-to-jcenter的引用 然后看看能不能编译成功

**Comment by fangyucun** [comment]
你说的是apply from吗?

**Comment by Spoon2014** [comment]
No value has been specified for property 'packageName' 我也遇到这个问题 @fangyucun  你的那个咋设置的呀

**Comment by Spoon2014** [comment]
不好意思  没看仔细 没放model下..
