### ISSUE TITLE
How to upload my annotation processor?

### ISSUE THREAD

**Issue by TYZRPVX** [xiaopansky/android-library-publish-to-jcenter#10]
I have developed a library (See [HERE](https://github.com/TYZRPVX/Blossom)), which consists of two sub-libraries. One is `blossom` and the other one is `blossom-compiler`.

I have upload the `blossom` module using your project, but how can I upload the `blossom-compiler` which is a Java library ?

Thanks in advance.

**Comment by xiaopansky** [comment]
project.packaging=jar

**Comment by xiaopansky** [comment]
纯Java项目的 上传我也没有经验，不过你可以参考类似的项目，比如butterknife
