### ISSUE TITLE
执行bintrayUpload时报错：poms/pom-default.xml (No such file or directory)

### ISSUE THREAD

**Issue by fishyer** [xiaopansky/android-library-publish-to-jcenter#11]
Error:Execution failed for task ':ui:bintrayUpload'.
> java.io.FileNotFoundException: /Users/yutianran/Code/Android/AndroidLib/ui/build/poms/pom-default.xml (No such file or directory)

**Comment by xiaopansky** [comment]
在这个错误前面是不是还有
```
build/libs/***-javadoc.jar could not be found.
build/libs/***-sources.jar could not be found.
```

如果是这样的话说明你执行bintrayUpload的方式是在Android Studio的Gradle窗口中选择"Run *** bintrayUpload"，`请不要用这种方式执行bintrayUpload`

正确的姿势应该是在命令行中执行gradlew bintrayUpload
