### ISSUE TITLE
 No value has been specified for property 'packageName'

### ISSUE THREAD

**Issue by Joy-Whale** [xiaopansky/android-library-publish-to-jcenter#2]
您好 我的项目一直报这个错  但是我在配置文件中找不到这个属性啊

**Comment by xiaopansky** [comment]
这个属性不是额外配置文件中的，比较难定位问题，你先按照最新的文档升级一下相关插件，然后再试一下

**Comment by Joy-Whale** [comment]
我的插件应该都是最新的了

**Comment by xiaopansky** [comment]
我前两天用还是可以的 包括gradle版本 android studio版本等 都检查一下

**Comment by fangyucun** [comment]
我用https://raw.githubusercontent.com/xiaopansky/android-library-publish-to-jcenter/master/bintrayUpload.gradle报找不到support包, 
用离线的那个改了下, 标题的这个错误.

**Comment by xiaopansky** [comment]
此问题已经发现并解决了，请查看首页readme最后的常见问题
