### ISSUE TITLE
Uploading .pom failed, response 400

### ISSUE THREAD

**Issue by captainbupt** [xiaopansky/android-library-publish-to-jcenter#4]
你好，我的错误如下。aar已经上传成功，但是pom始终无法上传成功。在bintray上也已经显示出来了，但是因为缺少pom，无法发布到jcenter。请问可能时什么原因造成的？

> 10:41:14.413 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@3050d479
> 10:41:14.413 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Connection can be kept alive indefinitely
> 10:41:14.415 [INFO] [org.gradle.api.Task] Uploading to https://api.bintray.com/content/captainbupt/maven/Ultra-Pull-to-Refresh-with-Load-More/1.0/in/srain/cube/ptr-lib/1.0/ptr-lib-1.0.pom...
> 10:41:14.416 [DEBUG] [groovyx.net.http.HTTPBuilder] PUT https://api.bintray.com/content/captainbupt/maven/Ultra-Pull-to-Refresh-with-Load-More/1.0/in/srain/cube/ptr-lib/1.0/ptr-lib-1.0.pom
> 10:41:14.416 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://api.bintray.com
> 10:41:14.416 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Stale connection check
> 10:41:14.418 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
> 10:41:14.418 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
> 10:41:14.418 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthentication] Proxy auth state: UNCHALLENGED
> 10:41:14.418 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
> 10:41:14.418 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: PUT /content/captainbupt/maven/Ultra-Pull-to-Refresh-with-Load-More/1.0/in/srain/cube/ptr-lib/1.0/ptr-lib-1.0.pom HTTP/1.1
> 10:41:15.332 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 400 Bad Request
> 10:41:15.333 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Connection can be kept alive indefinitely
> 10:41:15.333 [DEBUG] [groovyx.net.http.HTTPBuilder] Response code: 400; found handler: com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure8_closure35_closure37_closure39@137d04d8

**Comment by xiaopansky** [comment]
从你贴出来的日志上看并没有什么异常，都是说成功，你先查下本地build下生成pom有没有成功

**Comment by captainbupt** [comment]
本地library目录下的有build/poms/pom-default.xml，这个是目标文件嘛？

**Comment by xiaopansky** [comment]
应该是这个

**Comment by captainbupt** [comment]
那有什么可能出错嘛，比如命名上的问题，导致上传的路径非法？gradle基本也就只返回了一个400，没有其他提示信息了。。

> 10:41:14.418 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: PUT /content/captainbupt/maven/Ultra-Pull-to-Refresh-with-Load-More/1.0/in/srain/cube/ptr-lib/1.0/ptr-lib-1.0.pom HTTP/1.1
> 10:41:15.332 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 400 Bad Request

**Comment by xiaopansky** [comment]
Ultra-Pull-to-Refresh-with-Load-More 这个是你自己的项目吗？

**Comment by captainbupt** [comment]
我fork后补充的，原项目名为android-Ultra-Pull-To-Refresh。然后我保持了groupid没变，artifactId是使用的我自己的，这边会产生冲突嘛？

**Comment by xiaopansky** [comment]
groupid也换成你自己的试试

**Comment by captainbupt** [comment]
还是一样的效果。
> \* What went wrong:
> Execution failed for task ':ptr-lib:bintrayUpload'.
> \> Could not upload to 'https://api.bintray.com/content/captainbupt/maven/Ultra-Pull-to-Refresh-with-Load-More/1.0/com/captainbupt/ptr-lib/1.0/ptr-lib-1.0.pom': HTTP/1.1 400 Bad Request

**Comment by xiaopansky** [comment]
没辙了

**Comment by captainbupt** [comment]
好吧。。。其实我按你这个上传过一个库，已经成功了，但是这个就是不成功，我也没搞懂区别在哪。。

**Comment by captainbupt** [comment]
你好，有错误信息啦，不过我没看懂原因是什么，麻烦你帮我看下，谢谢～
> \* What went wrong:
> Execution failed for task ':ptr-lib:bintrayUpload'.
> \> Could not upload to 'https://api.bintray.com/content/captainbupt/maven/Ultra-Pull-to-Refresh-with-Load-More/1.0.0/in/srain/cube/ptr-lib/1.0.0/ptr-lib-1.0.0.pom': HTTP/1.1 400 Bad Request [message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'in/srain/cube/ptr-lib/1.0.0/ptr-lib-1.0.0.pom']

**Comment by xiaopansky** [comment]
跟你昨天贴出来的没有区别

**Comment by captainbupt** [comment]
最下面有个message，你看有帮助嘛。

[message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'in/srain/cube/ptr-lib/1.0.0/ptr-lib-1.0.0.pom']

**Comment by xiaopansky** [comment]
升级版本试试比如升级到1.1.0 不想升级的的话就上bintray上把旧的版本删了

**Comment by captainbupt** [comment]
我知道问题在哪了，它上传的路径为in/srain/cube/ptr-lib，也就是artifact是ptr-lib，但是我设置的artifacts是ultra-ptr-load-more。刚刚把它改成ptr-lib就可以了。请问这个上传路径是不是你的bintrayUpload.gradle里面定义的？应该是一个可以解决的bug。

**Comment by xiaopansky** [comment]
in/srain/cube/ptr-lib中的ptr-lib是默认取的module的名字，这个貌似改不了（没找到修改的方法），artifactId要和module名字一致，我用的时候都是保持一致的

**Comment by captainbupt** [comment]
好吧，谢谢你的帮助，问题解决了～

**Comment by xiaopansky** [comment]
这还是你自己解决的 我要把这种情况写到WIK上

**Comment by captainbupt** [comment]
那你也可以把gradle-bintray-plugin的版本改成1.2了。。。1.0看不到message，所以之前会比较瞎。。

**Comment by xiaopansky** [comment]
OK
