### ISSUE TITLE
没有配置 version 的地方

### ISSUE THREAD

**Issue by 13120241790** [xiaopansky/android-library-publish-to-jcenter#9]
没有配置 version 的地方

**Comment by xiaopansky** [comment]
version自动取build.gradle里的versionName和versionCode

**Comment by 13120241790** [comment]
哥  版本迭代怎么弄呢？ 比如 1.0.0 > 1.0.1 > 1.0.2 只换个版本号就够了吗

**Comment by xiaopansky** [comment]
是的 改版本号和版本名就行了
